### ISSUE TITLE
Are metabolites hard coded- if so can we review them and change them to:

### ISSUE THREAD

**Issue by SJCalvert** [IanCal/sparta-data-entry#4]
List of Metabolites:
Proton (if needed)
Cu Glucose
Cu Fructose
C1 Pyruvate
Cu glucose and C1 pyruvate
Cu fructose and C1 pyruvate
Cu Galactose
C1 butyrate
Additional Substrate 1
Additional Substrate 2
Additional Substrate 3

**Comment by IanCal** [comment]
Should be ready for checking.
